### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by DarkCrystalll** [glisco03/conjuring#53] opened 2022-11-28 07:14 UTC
[minecraft-exported-crash-info-2022-11-28T15-08-38.zip](https://github.com/wisp-forest/conjuring/files/10101333/minecraft-exported-crash-info-2022-11-28T15-08-38.zip)

**Comment by gliscowo** [comment] 2022-11-28 10:38
Duplicate of #51

**Closed as completed by gliscowo** 2022-11-28 10:38 UTC
