### ISSUE TITLE
Вылетает Майнкрафт

### ISSUE THREAD

**Issue by Apple025** [glisco03/conjuring#64] opened 2024-03-25 09:57 UTC
При использовании ПКМ (Right Click) Infernal Scepter, вылетает Майнкрафт, играю на версии 1.20.1, Patchouli 1.20.1–84
Прикрепил crah-report
[crash-2024-03-25_14.48.44-client.txt](https://github.com/wisp-forest/conjuring/files/14741799/crash-2024-03-25_14.48.44-client.txt)

**Comment by gliscowo** [comment] 2024-04-29 21:28
While I appreciate that you presumably do not speak English well, I do not speak or understand Russian at all - thus I ask you kindly to try using a translator when communicating with us. Now, I'm not quite sure what made you mention the Infernal Scepter, after all that is an item from Things (a separate mod) and the crash you linked is (likely) caused by the Superior Conjuring Scepter. 

Either way, this crash is almost certainly a duplicate of #54 and thus I'll be closing it in favor of that other issue
Cheers

**Closed as not planned by gliscowo** 2024-04-29 21:28 UTC
