### ISSUE TITLE
Crash when using active ability (if particles turned off)

### ISSUE THREAD

**Issue by RandomDude123123** [glisco03/conjuring#54] opened 2022-12-30 05:16 UTC
HI,

When using the active ability of the soul sword and soul alloy pickaxe it crashes the game, but only if particles are turned off. It also causes other players in the vicinity to crash, if particles are turned off.

Attached 2 reports.
[crash-2022-12-30_05.04.37-client.txt](https://github.com/wisp-forest/conjuring/files/10323191/crash-2022-12-30_05.04.37-client.txt)
[crash-2022-12-30_05.10.44-client.txt](https://github.com/wisp-forest/conjuring/files/10323192/crash-2022-12-30_05.10.44-client.txt)

**Comment by gliscowo** [comment] 2023-05-30 20:35
Do you have any more insight into this? Neither have we been able to reproduce this nor gather any significant information from the crash reports you attached. If not, I'll assume this is no longer relevant and close it soon

Cheers

**Closed as completed** 2024-04-29 21:31 UTC
Labels: type: compatibility, status: investigating

**Comment by gliscowo** [comment] 2024-04-29 21:34
As visible above, I have altered the problematic code in owo-lib (to be released soon). Sadly, these changes will not be making it to versions of the game older than 1.20.5 (presumably).

Now, I can say that this is not vanilla behavior and most likely caused by some kind of optimization mod - I have no clue which one would responsible however. For anyone encountering this problem on an older version of the game I'm afraid the only solution is to identify and remove (or disable the offending feature) the conflicting optimization mod or re-enable particles
