### ISSUE TITLE
[Conjuring 1.19.2] Creative menu crash

### ISSUE THREAD

**Issue by kingkuys2123** [glisco03/conjuring#52] opened 2022-11-28 06:07 UTC
Minecraft 1.18.2
Fabric Loader 0.14.10
Fabric Api 0.67.1
Conjuring 1.0.25

- Game crashed when trying to get to the Conjuring mod's creative tab, might be the same as #51 

[crash-2022-11-28_13.02.08-client.txt](https://github.com/wisp-forest/conjuring/files/10100933/crash-2022-11-28_13.02.08-client.txt)
[latest.log](https://github.com/wisp-forest/conjuring/files/10100934/latest.log)

**Comment by gliscowo** [comment] 2022-11-28 10:38
Duplicate of #51

**Closed as completed by gliscowo** 2022-11-28 10:38 UTC
