### ISSUE TITLE
Gem tinker disappears

### ISSUE THREAD

**Issue by Hero9909** [glisco03/conjuring#12] opened 2021-06-26 12:48 UTC
version 1.0.3 beta mc 1.17 fabric 11.3
upon initiating the crafting progress for a haste gem the tinkerer and its resources disapears

**Comment by Spacecooki** [comment] 2021-07-01 19:01
I have the same problem, but with both Emeralds, Eyes, Rubys and Lapis

**Comment by gliscowo** [comment] 2021-07-01 19:15
I would suspect Carrier being at fault here. Try either disabling it or putting your keybind on something other than shift

**Comment by Spacecooki** [comment] 2021-07-01 19:41
Tried to swap the "sneak" from shift to another keybinding but the whole thing still dissapears.
When I sneak to press it, I suddenly collect all of the gems but the lesser soul essence is still left. So I try to put the gems back but as soon as I do that the whole thing dissapears

**Comment by gliscowo** [comment] 2021-07-01 19:43
You're obviously having some kind of incompatibility, you'll have to go and find out which mod is causing it

**Comment by Noaaan** [comment] 2021-07-01 19:59
Does disabling Carry fix the issue?

**Comment by AGUrGrill** [comment] 2021-07-25 04:16
I am having the same issue with version 1.0.5 on fabric.

**Comment by gliscowo** [comment] 2021-07-25 19:44
> Does disabling Carry fix the issue?

Has anyone who is affected by this problem tried this?

**Comment by AGUrGrill** [comment] 2021-07-25 20:23
I did not realize that was a mod lol. After changing its keybind everything works as intended, thanks!

**Comment by gliscowo** [comment] 2021-08-24 15:03
Seeing as every other known case of this was caused by Carrier and the fact the original author hasnt responded in over a month I will now close this as resolved

**Closed by gliscowo** 2021-08-24 15:03 UTC
