### ISSUE TITLE
Interference with the Big Torch from the Kibe mod 

### ISSUE THREAD

**Issue by meecosha** [glisco03/conjuring#26] opened 2021-12-21 00:02 UTC
When the Big Torch is on, it stops the mobs from spawning from the Conjurer. But the minecraft spawners still work, so it's the issue with the Conjurer spawners. Thank you!

**Comment by gliscowo** [comment] 2021-12-30 22:30
Unless I am completely mistaken, I have just verified in development that the Big Torch does in fact also block the vanilla mob spawner. Unless you can give a scenario where a vanilla spawner works, I'll close this as intended behaviour
Cheers

**Closed as completed by gliscowo** 2021-12-30 22:30 UTC
Labels: status: invalid

**Comment by meecosha** [comment] 2021-12-31 18:04
Yes, sorry. You are correct
