### ISSUE TITLE
gem tinkerer disappears

### ISSUE THREAD

**Issue by meimme** [glisco03/conjuring#22] opened 2021-11-03 22:53 UTC
When Conjuring (1.0.12) is used on the modpack "Medieval Minecraft". Using the gem tinkerer with shift+right click made it disappear.

**Comment by Noaaan** [comment] 2021-11-04 00:28
Update to latest version, this is a duplicate of #20 and has been fixed.

**Closed as completed by Noaaan** 2021-11-04 00:28 UTC
Labels: type: duplicate
