### ISSUE TITLE
The Enchiridion won't open

### ISSUE THREAD

**Issue by ravensniper72** [glisco03/conjuring#9] opened 2021-06-17 01:14 UTC
I try to right click with it to read it and it just acts like im pushing a button. I'm using the 1.17 version.

**Comment by glisco03** [comment] 2021-06-17 05:11
Heyo, this is not a bug per-se but simply me waiting on patchouli to be released for 1.17. Thanks for reporting it though, I should probably mention this somewhere

**Comment by ravensniper72** [comment] 2021-06-17 05:35
I suggest even just a online copy of what the book has in it for the time being would be nice. I'm new to the mod along with a few people on my server and we have no clue what to do for it lol.

**Comment by glisco03** [comment] 2021-06-17 05:37
Yea, that's a pretty good idea. I'll probably go and upload screenshots of all pages somewhere later today.
Ready to see patchouli update 2 minutes after I do that xD

**Comment by ravensniper72** [comment] 2021-06-17 07:30
Lol right

**Comment by glisco03** [comment] 2021-06-17 16:17
https://imgur.com/a/jJzZfZW

Here you go, this is the entire Enchiridion. Reading it like this is gonna be a bit painful but it's the best I can do for now

**Comment by glisco03** [comment] 2021-06-24 15:56
Fixed in newest release

**Closed by glisco03** 2021-06-24 15:56 UTC
Labels: enhancement
