### ISSUE TITLE
Error when trying to create any of the Aspect Gems

### ISSUE THREAD

**Issue by OfficialLambdax** [glisco03/conjuring#20] opened 2021-10-20 22:48 UTC
A player of our Server reports a bug with this mod at version 1.0.12 for fabric.

He tried to create Aspect Gems and in the process where he needed to SHIFT + Right click the item, it vanished and the Server reported the Error below

```
[00:43:14] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "com.glisco.conjuring.blocks.gem_tinkerer.GemTinkererBlockEntity.getInventory()" because the return value of "net.minecraft.class_1937.method_8321(net.minecraft.class_2338)" is null
        at com.glisco.conjuring.blocks.gem_tinkerer.GemTinkererBlock.method_9536(GemTinkererBlock.java:128) ~[conjuring-1.0.12.jar:?]
        at net.minecraft.class_4970$class_4971.method_26197(class_4970.java:914) ~[intermediary-server.jar:?]
        at net.minecraft.class_2818.method_12010(class_2818.java:297) ~[intermediary-server.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:211) ~[intermediary-server.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:196) ~[intermediary-server.jar:?]
        at net.minecraft.class_1937.method_8650(class_1937.java:271) ~[intermediary-server.jar:?]
        at me.steven.carrier.impl.CarriableGeneric.tryPickup(CarriableGeneric.java:50) ~[carrier-1.8.0.jar:?]
        at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:35) ~[carrier-1.8.0.jar:?]
        at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:74) ~[carrier-1.8.0.jar:?]
        at net.minecraft.class_4970$class_4971.handler$zdk000$carrier_interactBlock(class_4970.java:1116) ~[intermediary-server.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:938) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:327) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1050) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[intermediary-server.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Noaaan** [comment] 2021-10-20 23:43
This is a duplicate of issue #12 
We are looking at a fix, but for now re-binding your carrier keybind, or enabling the carrier glove in their config prevents this crash.

**Comment by OfficialLambdax** [comment] 2021-10-21 11:07
The key is located under "category.carrier" in fiel "carrier.key" instead of in the Conjuring category (Just in case someone wonders). Changing the key, or in our case giving it a key since none was set to it, helped (:

**Comment by gliscowo** [comment] 2021-11-03 17:54
Fixed in latest

**Closed as completed by gliscowo** 2021-11-03 17:54 UTC
Labels: type: bug, type: duplicate
