### ISSUE TITLE
Slimes don't play nice

### ISSUE THREAD

**Issue by DelilahEve** [glisco03/conjuring#27] opened 2021-12-28 14:36 UTC
Noticed a few issues with slimes:

1. only the small slimes can be used in the Ritual of Extraction, the ritual always fails otherwise
    a. large/medium slimes will also spawn medium/small slimes respectively with no AI

2. Conjurer will not spawn slimes
    a. this may be due to the positioning of the Conjurer (not in a slime chunk, and above y=40)
    
Tested with a normal Conjuring Focus, in a Soul Sand biome, using 4 Blackstone Pedestal, all with slime balls, and properly linked to the Soul Funnel.

Conjurer failing to spawn:
https://i.imgur.com/gxZmzwO.gifv

Conjurer setup:
![spawner_setup](https://user-images.githubusercontent.com/2165106/147576804-2558d3b3-84af-4999-a259-d3ffcf8d664a.png)

Altar setup:
![image](https://user-images.githubusercontent.com/2165106/147576914-c3b9717b-84ad-4890-8217-d875cf5148fb.png)

**Comment by Noaaan** [comment] 2021-12-28 17:20
The first part of the issue is likely related to the fact that medium/large slimes do not have a loot table. They simply split into smaller slimes on death, meaning the chance of the Ritual of Extraction suceeding is low (in theory it should be possible, needs further testing).  

The second issue is also a known one, which manifests because Conjuring copies the mob spawner logic from vanilla Minecraft. This gives it multiple quirks, like having to respect slime chunks when spawning slimes, and animals requiring grass blocks to spawn on.

**Comment by gliscowo** [comment] 2021-12-29 14:18
I'll close this for now, as this is all either intended behavior or simply a consequence of how Slimes work

**Closed as completed by gliscowo** 2021-12-29 14:18 UTC
